local addonName, SB = ...
local Add = SB.Database.AddSpell -- Короткая ссылка

Add({
    id = "mage_shield",
    name = "Магический доспех",
    key = "Отречение",
    icon = "Interface\\Icons\\Spell_magearmor",
    level = 1,
    class = "Маг",
    description = "Щит создаёт вокруг мага кратковременный арканный барьер, снижающий получаемый магический урон. Потоки энергии перенаправляют враждебные заклинания, невилируя  слабое стихийное и магическое воздействие для заклинателя.",
	duration = 10,
    isConcentration = false,
	container = "eff_mage_shield",
    caura = 151,
	scaling = {
		hit    = { ["Наука"] = 1, ["Эрудиция"] = 0.5 },
	},
})
Add({
    id = "fireball",
    name = "Огненный шар",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_fire_flamebolt",
    level = 3,
    class = "Маг",
    damageType = "fire",
    caura = 1209,
    description = "Маг запускает нестабильный сгусток пламени, который детонирует в указанной точке. Взрыв наносит урон огнём всем противникам в области и опаляет их, оставляя тлеющие ожоги на несколько секунд.",
    resistable = true,
    canCrit = true,
	distance = 30,
	aoe = { radius = 6 },
	debuff = "eff_burn",
	duration = 3,
	scaling = {
		hit    = { ["Наука"] = 1 },
		crit   = { ["Анализ"] = 1.5 },
		damage = { ["Интеллект"] = 1.27 },
	},
})
Add({
    id = "arcane_blast",
    name = "Чародейская вспышка",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_arcane_blast",
    level = 1,
    class = "Маг",
    damageType = "arcane",
    caura = 576,
    description = "Вы выпускаете в мир вспышку чистой чародейской энергии, разрывая пространство ослепительным импульсом. Волна поражает врага в зоне вашей видимости, нанося урон тайной магией и оставляя в воздухе дрожащий след силы, лишающий чародея контроля над собственной энергией. Она становится разрушительнее, но и силы вытекают из тела быстрее.",
    resistable = true,
    canCrit = true,
	distance = 30,
    duration = 3,
	container = "eff_arcane_blast",
	scaling = {
		hit    = { ["Наука"] = 2 },
		crit   = { ["Анализ"] = 1 },
        damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "spell_blade",
    name = "Чародейский клинок",
    requirement = "melee",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_weapon_shortblade_79",
    level = 0,
    class = "Маг",
    damageType = "arcane",
    caura = 411,
    description = "Вы направляете магическую силу сквозь сталь, превращая оружие в проводник разрушительной энергии. Чародейский клинок сочетает грубую мощь воина с точностью волшебника. Каждый взмах оставляет в воздухе мерцающий след, а клинок звучит, словно разрывая саму ткань магии.",
    resistable = true,
    canCrit = true,
	duration = 2,
	debuff = "eff_spell_blade",
	distance = 2.5,
	scaling = {
		hit    = { ["Искусность"] = 1 },
		crit   = { ["Мощь"] = 1.5 },
		damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "ray_of_frost",
    name = "Морозный луч",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_mage_rayoffrost",
    level = 2,
    class = "Маг",
    damageType = "frost",
    caura = 87,
    description = "Ледяной луч пронзает цель, обжигая её холодом. Противник получает урон от холода и на короткое время замедляется.",
    resistable = true,
    canCrit = true,
	distance = 20,
	duration = 2,
    channel = 2,
	debuff = "eff_chilling",
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1.5 },
        damage = { ["Интеллект"] = 0.9 }
	},
})
Add({
    id = "fire_bolt",
    name = "Огненный снаряд",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_fire_firebolt02",
    level = 0,
    class = "Маг",
    damageType = "fire",
    caura = 618,
    description = "Маг запускает быстрый заряд пламени, поражающий одну цель. Вспышка поджигает противника, заставляя его некоторое время получать дополнительный урон от огня.",
    resistable = true,
    canCrit = true,
	distance = 20,
	debuff = "eff_burn",
	duration = 2,
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1 },
	},
})
Add({
    id = "frost_bolt",
    name = "Ледяная стрела",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_frostbolt02",
    level = 1,
    class = "Маг",
    damageType = "frost",
    caura = 754,
    description = "Вы метаете в цель сгусток льда и танцующей синей энергии с пугающей скоростью, нанося ледяной и колющий урон одновременно, в зависимости от уровня заклинателя степень вреда возрастает: от колотых глубоких ранений, до округлых промежутков в плоти противника.",
    resistable = true,
    canCrit = true,
	distance = 30,
	debuff = "eff_chilling",
    duration = 3,
	scaling = {
		hit    = { ["Исток"] = 1 },
		crit   = { ["Анализ"] = 2 },
		damage = { ["Интеллект"] = 0.75 },
	},
})
Add({
    id = "arcane_missles",
    name = "Чародейские стрелы",
    duration = 2,
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_mage_arcanebarrage",
    level = 2,
    class = "Маг",
    damageType = "arcane",
    caura = 1142,
    description = "Сгусток чистой чародейской энергии срывается с пальца и безошибочно поражает цель тайной магией — даже в ближнем бою, если у цели нет полного укрытия или полной маскировки. Выбрать часть тела нельзя; неодушевлённым предметам урона нет.\n\nСнарядов больше с ростом мастерства: два у адепта, три у эксперта. Их можно направить в одну или в разные цели, но каждый поражает только одно существо.",
    resistable = false,
    canCrit = true,
    channel = 2,
	distance = 30,
	scaling = {
		damage = { ["Интеллект"] = 0.8 },
	},
})
Add({
    id = "fire_hands",
    name = "Огненные ладони",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_fire_fireball",
    level = 1,
    class = "Маг",
    damageType = "fire",
    caura = 228,
    description = "Из рук мага вырывается широкий конус пламени, обжигая всех противников перед ним. Огонь также поджигает горючие цели, оставляя на них кратковременный эффект горения.",
    resistable = true,
    canCrit = true,
	aoe = { radius = 6 },
	debuff = "eff_burn",
	duration = 2,
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 0.5 },
		damage = { ["Интеллект"] = 0.75 },
	},
})
Add({
    id = "frost_glacier",
    name = "Конус холода",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_glacier",
    level = 3,
    class = "Маг",
    damageType = "frost",
    caura = 651,
    description = "Маг выпускает перед собой волну ледяного воздуха. Все противники в области получают урон от холода и на несколько секунд замедляются.",
    resistable = true,
    canCrit = true,
	aoe = { radius = 9 },
	debuff = "eff_chilling",
    duration = 3,
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 0.5 },
		crit   = { ["Анализ"] = 2 },
		damage = { ["Интеллект"] = 1.27 },
	},
})
Add({
    id = "clap_of_thunder_mage",
    name = "Раскат грома",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_thunderking_thunderstruck",
    level = 2,
    class = "Маг",
    damageType = "nature",
    caura = 978,
    description = "Вы с силой ударяете по земле, порождая чудовищный грохот, разрывающий барабанные перепонки врагов. Все существа в области (кроме вас) получают урон звуком, становящимся сильнее в зависимости от уровня заклинателя. Существа, получившие урон от этого эффекта, потрясаются звуковой энергией и замедляются (как под эффектом замораживания) на 1 полный раунд.",
    resistable = true,
    canCrit = true,
	duration = 1,
    isConcentration = false,
	distance = 20,
	debuff = "eff_chilling",
	aoe = { radius = 6 },
	scaling = {
		hit    = { ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 0.9 },
	},
})
Add({
    id = "arcane_barrage",
    name = "Чародейский обстрел",
    key = "Воплощение",
    damageType = "arcane",
    icon = "Interface\\Icons\\Ability_mage_arcanebarrage",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Вы выпускаете в мир стремительные стрелы из чистой чародейской энергии, пронзающие пространство на пути к цели. Сгустки врезаются во врагов с ослепительной вспышкой, оставляя за собой мерцающий след и обжигая тело тайной силой. Если у вас есть заряд чародейской энергии, обстрел расходует его.",
    resistable = true,
    canCrit = true,
    duration = 3,
    isConcentration = false,
	distance = 30,
    debuff = "eff_arcane_barrage",
	aoe = { radius = 6 },
	scaling = {
		hit    = { ["Науки"] = 1 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 1 },
	},
})

Add({
    id = "scorching_ray",
    name = "Испепеляющий луч",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_mage_firestarter",
    level = 2,
    class = "Маг",
    damageType = "fire",
    caura = 574,
    description = "Вы выпускаете дугу концентрированного пламени, создавая по одному лучу за каждую степень развития мага (ученик, адепт, эксперт), наносящую огненный урон, прожигая насквозь деревянные и хрупкие объекты.\n\nВы можете направить все лучи в одну цель или распределить их между несколькими целями, но все они должны находиться в пределах 9 м друг от друга. Все лучи выстреливают одновременно.",
    resistable = true,
    canCrit = true,
	duration = 1,
	debuff = "eff_burn",
    channel = 2,
	distance = 20,
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Исток"] = 0.5 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 1.55 },
	},
})
Add({
    id = "ice_spear",
    name = "Ледяное копьё",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_frostblast",
    level = 1,
    class = "Маг",
    damageType = "frost",
    caura = 178,
    description = "Вы призываете силы элементального плана, сгущаете стихии вокруг и выпускаете из ладони ледяное копьё, летящий прямо в выбранную цель. Мчащееся словно пуля ледяное копье вонзится точно в цель, но из-за мистических свойств, вред будет значительнее если цель значительно подморозить, чтобы усугубить обморожение.",
    resistable = true,
    canCrit = true,
	distance = 30,
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Исток"] = 0.5 },
		crit   = { ["Анализ"] = 2 },
		damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "mana_gem",
    name = "Самоцвет маны",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_misc_gem_sapphire_02",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Используя пустой кристалл маны, вы наполняете его частью своей магической силы, превращая в переносное хранилище магии. Этот предмет можно разрушить и впитать ману обратно: самоцвет возвращает 1 или 2 единицы маны, зависимо от того, сколько её в него вложено.\n\nВы можете поддерживать только один магический самоцвет.",
    resistable = true,
    isConcentration = false,
    creates = "item_mana_gem",
	scaling = {
		hit    = { ["Наука"] = 1, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "mage_lightning",
    name = "Молния",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_nature_lightningoverload",
    level = 3,
    class = "Маг",
    caura = 91,
    description = "С кончиков пальцев срывается ослепительная молния и бьёт всех существ на своём пути электричеством. Она поджигает горючее, повреждает предметы и плавит легкоплавкие металлы — свинец, золото, серебро, медь, бронзу.\n\nЕсли удар разрушает преграду, молния идёт дальше в пределах дальности; иначе останавливается у препятствия, как большинство магических эффектов.",
    resistable = true,
    canCrit = true,
	distance = 30,
	scaling = {
		hit    = { ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 1.6 },
	},
})
Add({
    id = "dragon_breath",
    name = "Дыхание дракона",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_misc_head_dragon_01",
    level = 4,
    class = "Маг",
    damageType = "fire",
    caura = 759,
    description = "Вы выдыхаете изо рта перед собой резкий поток пламени, вызывающий мучительные ожоги  у всех кто находится перед вами; у основания вашего рта пламя столь высоких температур, что в теории, при должной настойчивости способно оплавить металл, но есть все риски потерять лицо, в буквальном смысле!",
    resistable = true,
    canCrit = true,
	aoe = { radius = 6 },
	scaling = {
		hit    = { ["Исток"] = 1.5 },
		crit   = { ["Анализ"] = 1.5 },
		damage = { ["Интеллект"] = 3.6 },
	},
})
Add({
    id = "frost_nova",
    name = "Кольцо льда",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_freezingbreath",
    level = 1,
    class = "Маг",
    damageType = "frost",
    caura = 577,
    description = "Всплеск льда и холода детонирует с пронзительным визгом, нанося урон холодом всем существам в области; успешный спасбросок вдвое сокращает урон. Предметы вокруг тоже страдают.\n\nМаг указывает место взрыва — дальность и высоту; область — радиус 3 метра при высоте всего 30 сантиметров, её наклон маг задаёт сам. Задетых холод пронзает до сути и замедляет.",
    resistable = true,
    canCrit = true,
	aoe = { radius = 12 },
	duration = 2,
	debuff = "eff_chilling",
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Исток"] = 0.5 },
		crit   = { ["Анализ"] = 1.5 },
	},
})

Add({
    id = "mana_burst",
    name = "Чародейская вспышка",
    key = "Отречение",
    icon = "Interface\\Icons\\Ability_argus_soulburst",
    level = 3,
    class = "Маг",
    damageType = "arcane",
    caura = 364,
    description = "Вы создаете область магической нестабильности вокруг себя, вызывая возмущения в пространстве; магические энергии восстают против своих заклинателей, и наносят им вред равноценный их уровню соответственно кругам заклинаний; в случае если более пяти заклятий обращаются против заклинателей, в пространстве создаётся разрыв вызывающий прорыв манадемонов.",
    resistable = true,
    canCrit = true,
    isConcentration = false,
	aoe = { radius = 6 },
	scaling = {
		hit    = { ["Наука"] = 1 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 1.77 },
	},
})

Add({
    id = "undetectable",
    name = "Необнаружимость",
    key = "Отречение",
    icon = "Interface\\Icons\\Inv12_apextalent_mage_touchofthearchmage",
    level = 3,
    class = "Маг",
    caura = 98,
    description = "Существо или предмет скрыты от прорицания: их не выдают ни местоположение, ни аура, ни голос, ни облик, и никакое обнаружение — в том числе от магических предметов. На существе защита укрывает и его снаряжение.\n\nПрорицающий против защищённого проходит проверку прорицания с помехой, если наложивший защиту сильнее, и с преимуществом — если слабее.",
    resistable = true,
	duration = 1200,
    isConcentration = false,
	distance = 2.5,
    buff = "eff_undetectable",
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "antimagic",
    name = "Антимагия",
    key = "Отречение",
    icon = "Interface\\Icons\\Spell_frost_iceshock",
    level = 3,
    class = "Маг",
    caura = 734,
    description = "Заклинание снимает чары с существа или предмета, на время подавляет волшебный предмет, гасит эффекты в области или, как контрзаклинание, срывает чужое колдовство. Рассеять можно не всё.\n\nМгновенные эффекты не снимаются: они случаются быстрее, чем рассеивание вступит в силу, — огненный шар уже обжёг, окаменевшего не оживить.\n\nПрименяется одним из трёх способов: на цель, по области или как контрзаклинание.",
    resistable = true,
	distance = 30,
	dispel = { "magic" },
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "abonish_magic",
    name = "Ослабление магии",
    key = "Отречение",
    icon = "Interface\\Icons\\Spell_magic_managain",
    level = 1,
    class = "Маг",
    caura = 98,
    description = "Заклинание создаёт ауру вокруг цели, которая ослабляет часть эффектов всех исцеляющих и наносящих урон заклинаний на 1 круг.",
    resistable = true,
	duration = 150,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_abonish_magic",
	scaling = {
		hit    = { ["Наука"] = 1, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "mage_slow",
    name = "Замедление",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_nature_slow",
    level = 3,
    class = "Маг",
    caura = 735,
    description = "Маг искажает течение времени вокруг противника. Его скорость передвижения и применения способностей уменьшается, а частота атак становится ниже.",
    resistable = false,
	duration = 2,
    isConcentration = false,
	distance = 30,
	debuff = "eff_slowed_mage_slow",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})

Add({
    id = "dark_vision",
    name = "Темное зрение",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Inv_12_trinket_raid_voidspire_int1_voiddragoneye",
    level = 1,
    class = "Маг",
    caura = 167,
    description = "Субъект получает возможность видеть в полной темноте в радиусе 18 м. Темновиденье дает возможность видеть только в черно-белом цвете. Заклинание темновиденья не дает возможности видеть в магической темноте.",
    resistable = true,
	duration = 1200,
    isConcentration = false,
	distance = 2.5,
    buff = "eff_dark_vision",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "blink",
    name = "Скачок",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_arcane_blink",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Окутавшись серебристым туманом, вы телепортируетесь на расстояние до 9 метров в свободное пространство, видимое вами.",
    duration = 1,
	container = "eff_blink",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "magicalsentry",
    name = "Чародейский интеллект",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_holy_magicalsentry",
    level = 1,
    class = "Маг",
    caura = 98,
    description = "Это заклинание делает существо умнее, что влияет на проверки требующие интеллектуальной или иной деятельности; от повышения интеллекта не прибавляется мана, но в случае соревования с другими волшебниками (например, при использовании рассеивания или контрзаклинания), они получают право дополнительного преимущества.",
    resistable = true,
	duration = 150,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_owl_wisdom_arcaneintellect",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "arcaneintellect",
    name = "Чародейская гениальность",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_holy_arcaneintellect",
    level = 3,
    class = "Маг",
    caura = 98,
    description = "Опытный волшебник прикладывает к виску пальцы, обостряя собственный ум. Эхо данного заклинания так сильно, что оно транслируется на окружающих соратников делая их умнее, что влияет на проверки требующие интеллектуальной или иной деятельности.",
    resistable = true,
	duration = 150,
    isConcentration = false,
	aoe = { radius = 18 },
	buff = "eff_owl_wisdom_arcaneintellect",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "mage_featherfall",
    name = "Падение перышком",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_magic_featherfall",
    level = 1,
    class = "Маг",
    caura = 735,
    description = "Маг замедляет падение союзников, превращая стремительное падение в плавное скольжение. Цели под действием эффекта не получают урона при приземлении.",
    resistable = true,
	duration = 5,
    isConcentration = false,
	distance = 2.5,
    buff = "eff_mage_featherfall",
	scaling = {
		hit    = { ["Наука"] = 1.5 },
	},
})
Add({
    id = "mana_water",
    name = "Создание воды маны",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_12_profession_enchanting_manaoil_blue",
    level = 1,
    class = "Маг",
    caura = 961,
    description = "Это заклинание наполняет пустой флакон прозрачной водой. Если заклинатель выпивает эту воду, он восстанавливает ману, которой хватит на заклинание до 3-го круга (по выбору пьющего). ",
    resistable = true,
    isConcentration = false,
    creates = "item_mana_water",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "mana_food",
    name = "Сотворение пищи",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_misc_food_73cinnamonroll",
    level = 1,
    class = "Маг",
    caura = 961,
    description = "Это заклинание создаёт две буханки кислого хлеба. Съев одну буханку (что занимает 5 последовательных и непрерываемых раундов), существо восстанавливает здоровье.\n\nПо окончании действия заклинания все несъеденные буханки исчезают.",
    resistable = true,
    isConcentration = false,
    creates = "item_mana_food",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "frost_armor_mage",
    name = "Ледяной доспех",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_frostarmor02",
    level = 0,
    class = "Маг",
    caura = 807,
    description = "Аура холода укрывает мага от физического и огненного урона: удар клинком, что мог стать смертельным, оставит лишь рану, а царапина отразится от хлада. Движений доспех не стесняет.\n\nОн не пускает бестелесных существ и защищает от одержимости призраками. Кто бьёт мага телом или оружием ближнего боя, урон наносит, но сам охлаждается; оружие с большой досягаемостью, вроде длинных копий, от этого избавлено.",
	duration = 600,
    isConcentration = false,
	container = "eff_frost_armor_mage",
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 0.5 },
	},
})
Add({
    id = "summon_familiar",
    name = "Волшебный фамилиар",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_socererking_arcanemines",
    level = 2,
    class = "Маг",
    caura = 1301,
    description = "Маг призывает фамильяра — воплощение собственной силы, отзывающееся на его чары.\n\nКаждое заклинание мага находит в фамильяре отклик: вредоносные повторяются усиленным отголоском, а полезные и защитные ложатся и на него самого. Так он следует за магом, усиливая его атаки.\n\nСвоей воли у фамильяра нет — лишь отражение магии хозяина.",
    duration = 150,
    isConcentration = false,
    container = "eff_summon_familiar",
})
Add({
    id = "image",
    name = "Образ",
    key = "Иллюзия",
    icon = "Interface\\Icons\\Inv_112_raidtrinkets_netheroverlaymatrix",
    level = 3,
    class = "Маг",
    caura = 98,
    description = "Маг создаёт сложную иллюзию, способную имитировать внешний вид, звук, запах и температуру. Образ можно перемещать и заставлять реагировать на происходящее вокруг.",
	duration = 3,
    isConcentration = false,
	distance = 20,
    container = "eff_image",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "blurred_image",
    name = "Размытый образ",
    key = "Иллюзия",
    icon = "Interface\\Icons\\Spell_nature_invisibilty",
    level = 3,
    class = "Маг",
    caura = 812,
    description = "Силуэт мага начинает мерцать и раздваиваться, затрудняя попадание по нему. Противники получают меньший шанс успешно поразить цель прямыми атаками.",
    resistable = true,
	duration = 20,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_evasion_blurred_image",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "mage_invisibility",
    name = "Невидимость",
    key = "Иллюзия",
    icon = "Interface\\Icons\\Ability_mage_invisibility",
    level = 2,
    class = "Маг",
    caura = 1,
    description = "Существо или предмет, которого коснулся маг, становится невидимым вместе со снаряжением — даже для ночного зрения и союзников без «видеть невидимое». Брошенное проявляется, подобранное — исчезает. Свет виден, источник — нет; торчащее дальше 3 м видно.\n\nНевидимка может говорить, открывать двери и отдавать приказы, но, напав сам, сразу становится видим.",
    resistable = true,
	duration = 10,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_stealth_mage_invisibility",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "disguise",
    name = "Маскировка",
    key = "Иллюзия",
    icon = "Interface\\Icons\\Ability_racial_dispelillusions",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Маг изменяет собственный облик, маскируя лицо, одежду, броню и снаряжение. Иллюзия меняет только внешний вид и не даёт цели чужих способностей.",
	duration = 100,
    isConcentration = false,
    container = "eff_disguise",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "detect_thougts",
    name = "Обнаружение мыслей",
    key = "Прорицание",
    icon = "Interface\\Icons\\Spell_arcane_focusedpower",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Маг проникает в поверхностные мысли ближайших существ. Чем дольше сохраняется концентрация, тем больше информации можно получить о присутствующих разумах и их намерениях.",
    resistable = true,
	duration = 3,
    isConcentration = false,
	distance = 20,
    channel = true,
    debuff = "eff_detect_thougts",
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Интуиция"] = 0.5 },
	},
})
Add({
    id = "see_invisible",
    name = "Видеть невидимое",
    key = "Прорицание",
    icon = "Interface\\Icons\\Spell_shadow_detectlesserinvisibility",
    level = 2,
    class = "Маг",
    caura = 167,
    description = "Магические искажения становятся видимыми для заклинателя. Невидимые и бестелесные существа в пределах обзора проявляются как полупрозрачные силуэты.",
	duration = 100,
    isConcentration = false,
    container = "eff_see_invisible",
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Интуиция"] = 0.5 },
	},
})
Add({
    id = "polymorph",
    name = "Полиморф",
    key = "Трансмутация",
    icon = "Interface\\Icons\\spell_nature_polymorph",
    level = 1,
    class = "Маг",
    caura = 98,
    description = "Маг превращает цель в безобидную форму зверя. Полиморфированное существо теряет доступ к своим обычным способностям и возвращается в исходную форму после разрушения эффекта или получения серьёзного повреждения.",
    resistable = true,
	duration = 3,
    isConcentration = false,
	distance = 30,
    debuff = "eff_polymorph",
	scaling = {
		hit    = { ["Наука"] = 1.5 },
	},
})Add({    id = "mage_anticurse",    name = "Развеять проклятие",	key = "Отречение",	icon = "Interface\\Icons\\Spell_nature_removecurse",    level = 1,    class = "Маг",	caura = 95,	description = "Позволяет магу разрушить цепи проклятий равных, или слабее третьему кругу; все проклятия на субъекте развеиваются, а использование заклятия на проклятом предмете позволяет от него избавиться, если проклятие лежащее на нем слабее, или равно третьему кругу магии.",	resistable = true,	distance = 40,	dispel = "curse",})
