local addonName, SB = ...
local Add = SB.Database.AddSpell -- Короткая ссылка

Add({
    id = "mage_shield",
    name = "Магический доспех",
    key = "Отречение",
    icon = "Interface\\Icons\\Spell_magearmor",
    level = 1,
    class = "Маг",
    description = "Щит создаёт вокруг мага кратковременный арканный барьер, снижающий получаемый магический урон. Потоки энергии перенаправляют враждебные заклинания, невилируя  слабое стихийное и магическое воздействие для заклинателя.",
    isCantrip = false,
    resistable = true,
	duration = 10,
    isConcentration = false,
	container = "eff_mage_shield",
    caura = 151,
	scaling = {
		hit    = { ["Наука"] = 1, ["Эрудиция"] = 0.5 },
	},
})
Add({
    id = "fireball",
    name = "Огненный шар",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_fire_flamebolt",
    level = 3,
    class = "Маг",
    damageType = "fire",
    caura = 1209,
    description = "Маг запускает нестабильный сгусток пламени, который детонирует в указанной точке. Взрыв наносит урон огнём всем противникам в области и опаляет их, оставляя тлеющие ожоги на несколько секунд.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	distance = 30,
	aoe = { radius = 5 },
	debuff = "eff_burn",
	duration = 3,
	scaling = {
		hit    = { ["Наука"] = 1 },
		crit   = { ["Анализ"] = 1.5 },
		damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "mage_lasso",
    name = "Лассо молнии",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_thunderking_lightningwhip",
    level = 1,
    class = "Маг",
    damageType = "nature",
    caura = 576,
    description = "Вы создаёте хлыст из молний, поражающий одно существо по вашему выбору, которое вы можете видеть в пределах 4.5 метрах от вас. Цель должна может пытаться сопротивляться, иначе будет притянута на 3 метра по прямой к вам, после чего получит урон электричеством, если окажется в пределах 1.5 метров от вас.",
    isCantrip = true,
    resistable = true,
    canCrit = true,
	distance = 20,
    channel = 2,
	scaling = {
		hit    = { ["Исток"] = 2 },
		crit   = { ["Анализ"] = 1 },
        damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "electric_shock",
    name = "Электрошок",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_shaman_crashlightning",
    level = 0,
    class = "Маг",
    damageType = "nature",
    caura = 411,
    description = "Маг выпускает короткую дугу молнии в ближайшего противника. Разряд наносит урон от электричества и на короткое время нарушает его реакции. По цели в металлической броне удар проходит особенно эффективно.",
    isCantrip = true,
    resistable = true,
    canCrit = true,
	distance = 2.5,
	scaling = {
		hit    = { ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1.5 },
		damage = { ["Интеллект"] = 0.65 },
	},
})
Add({
    id = "ray_of_frost",
    name = "Морозный луч",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_mage_rayoffrost",
    level = 2,
    class = "Маг",
    damageType = "frost",
    caura = 87,
    description = "Ледяной луч пронзает цель, обжигая её холодом. Противник получает урон от холода и на короткое время замедляется.",
    isCantrip = true,
    resistable = true,
    canCrit = true,
	distance = 20,
	duration = 2,
    channel = 2,
	debuff = "eff_chilling",
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1.5 },
        damage = { ["Интеллект"] = 1 }
	},
})
Add({
    id = "fire_bolt",
    name = "Огненный снаряд",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_fire_firebolt02",
    level = 0,
    class = "Маг",
    damageType = "fire",
    caura = 618,
    description = "Маг запускает быстрый заряд пламени, поражающий одну цель. Вспышка поджигает противника, заставляя его некоторое время получать дополнительный урон от огня.",
    isCantrip = true,
    resistable = true,
    canCrit = true,
	distance = 20,
	debuff = "eff_burn",
	duration = 2,
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1 },
	},
})
Add({
    id = "frost_bolt",
    name = "Ледяная стрела",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_frostbolt02",
    level = 1,
    class = "Маг",
    damageType = "frost",
    caura = 754,
    description = "Вы метаете в цель сгусток льда и танцующей синей энергии с пугающей скоростью, нанося ледяной и колющий урон одновременно, в зависимости от уровня заклинателя степень вреда возрастает: от колотых глубоких ранений, до округлых промежутков в плоти противника.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	distance = 30,
	debuff = "eff_chilling",
    duration = 3,
	scaling = {
		hit    = { ["Исток"] = 1 },
		crit   = { ["Анализ"] = 2 },
		damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "arcane_missles",
    name = "Чародейские стрелы",
    duration = 2,
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_mage_arcanebarrage",
    level = 1,
    class = "Маг",
    damageType = "arcane",
    caura = 1142,
    description = "Сгусток чистой чародейской энергии выстреливает из вашего пальца и безошибочно поражает цель, нанося урон тайной магией.\n\nСнаряд поражает безошибочно, даже если цель находится в ближнем бою и,  если цель не имеет полного укрытия или полной маскировки. Вы не можете выбирать для поражения конкретные части существа. Это заклинание не наносит урон неодушевлённым предметам.\n\nЗа каждые два уровня заклинателя после первого вы получаете один дополнительный снаряд: два на уровне адепта, три на уровне эксперта. Если вы выпускаете несколько снарядов, вы можете направить их в одно или в несколько существ. Один снаряд может поразить только одно существо.",
    isCantrip = false,
    resistable = false,
    canCrit = true,
    channel = 2,
	distance = 30,
	scaling = {
		damage = { ["Интеллект"] = 0.65 },
	},
})
Add({
    id = "fire_hands",
    name = "Огненные ладони",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_fire_fireball",
    level = 1,
    class = "Маг",
    damageType = "fire",
    caura = 228,
    description = "Из рук мага вырывается широкий конус пламени, обжигая всех противников перед ним. Огонь также поджигает горючие цели, оставляя на них кратковременный эффект горения.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	aoe = { radius = 6 },
	debuff = "eff_burn",
	duration = 2,
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 0.5 },
		damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "frost_glacier",
    name = "Конус холода",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_glacier",
    level = 3,
    class = "Маг",
    damageType = "frost",
    caura = 651,
    description = "Маг выпускает перед собой волну ледяного воздуха. Все противники в области получают урон от холода и на несколько секунд замедляются.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	aoe = { radius = 9 },
	debuff = "eff_chilling",
    duration = 3,
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 0.5 },
		crit   = { ["Анализ"] = 2 },
		damage = { ["Интеллект"] = 1.15 },
	},
})
Add({
    id = "clap_of_thunder_mage",
    name = "Раскат грома",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_thunderking_thunderstruck",
    level = 2,
    class = "Маг",
    damageType = "nature",
    caura = 978,
    description = "Вы с силой ударяете по земле, порождая чудовищный грохот, разрывающий барабанные перепонки врагов. Все существа в области (кроме вас) получают урон звуком, становящимся сильнее в зависимости от уровня заклинателя. Существа, получившие урон от этого эффекта, потрясаются звуковой энергией и замедляются (как под эффектом замораживания) на 1 полный раунд.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	duration = 1,
    isConcentration = false,
	distance = 20,
	debuff = "eff_chilling",
	aoe = { radius = 6 },
	scaling = {
		hit    = { ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "deafening_screech",
    name = "Оглушительный визг",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_evoker_oppressingroar",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Ваш голос превращается в пронзительный визг, усиленный магией, и воздействует на конусообразную область, исходящую из вашего рта. Все, кто находится в конусе и не преуспеет в защите, глохнут на время действия заклинания. Особенно хрупкие стеклянные изделия в области эффекта могут разбиться. ",
    isCantrip = false,
    resistable = true,
    canCrit = false,
    duration = 3,
    isConcentration = false,
	distance = 20,
    debuff = "eff_deafening_screech",
	scaling = {
		hit    = { ["Исток"] = 1 },
	},
})

Add({
    id = "scorching_ray",
    name = "Испепеляющий луч",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_mage_firestarter",
    level = 2,
    class = "Маг",
    damageType = "fire",
    caura = 574,
    description = "Вы выпускаете дугу концентрированного пламени, создавая по одному лучу за каждую степень развития мага (ученик, адепт, эксперт), наносящую огненный урон, прожигая насквозь деревянные и хрупкие объекты.\n\nВы можете направить все лучи в одну цель или распределить их между несколькими целями, но все они должны находиться в пределах 9 м друг от друга. Все лучи выстреливают одновременно.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	duration = 2,
    channel = 2,
	distance = 20,
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Исток"] = 0.5 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 1.5 },
	},
})
Add({
    id = "ice_spear",
    name = "Ледяное копьё",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_frostblast",
    level = 1,
    class = "Маг",
    damageType = "frost",
    caura = 178,
    description = "Вы призываете силы элементального плана, сгущаете стихии вокруг и выпускаете из ладони ледяное копьё, летящий прямо в выбранную цель. Мчащееся словно пуля ледяное копье вонзится точно в цель, но из-за мистических свойств, вред будет значительнее если цель значительно подморозить, чтобы усугубить обморожение.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	distance = 30,
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Исток"] = 0.5 },
		crit   = { ["Анализ"] = 2 },
		damage = { ["Интеллект"] = 1 },
	},
})
Add({
    id = "mana_gem",
    name = "Самоцвет маны",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_misc_gem_sapphire_02",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Используя пустой кристалл маны, вы наполняете его частью своей магической силы, превращая в переносное хранилище магии. Этот предмет можно разрушить и впитать ману обратно: самоцвет возвращает 1 или 2 единицы маны, зависимо от того, сколько её в него вложено.\n\nВы можете поддерживать только один магический самоцвет.",
    isCantrip = false,
    resistable = true,
    isConcentration = false,
    creates = "item_mana_gem",
	scaling = {
		hit    = { ["Наука"] = 1, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "mage_lightning",
    name = "Молния",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_nature_lightningoverload",
    level = 3,
    class = "Маг",
    damageType = "nature",
    caura = 91,
    description = "Вы выпускаете мощный поток электрической энергии, который вырывается из ваших кончиков пальцев в виде ослепительной молнии. Заряд поражает всех существ на своём пути, нанося урон электричеством.\n\nМолния воспламеняет горючие материалы и повреждает объекты, с которыми соприкасается. Она способна плавить металлы с низкой температурой плавления — такие как свинец, золото, серебро, медь и бронза.\n\nЕсли нанесённый урон разрушает преграду, заряд продолжает свой путь в пределах дистанции. В противном случае молния останавливается у препятствия, как и большинство других магических эффектов.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	distance = 30,
	scaling = {
		hit    = { ["Исток"] = 1 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 1.5 },
	},
})
Add({
    id = "dragon_breath",
    name = "Дыхание дракона",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_misc_head_dragon_01",
    level = 4,
    class = "Маг",
    damageType = "fire",
    caura = 759,
    description = "Вы выдыхаете изо рта перед собой резкий поток пламени, вызывающий мучительные ожоги  у всех кто находится перед вами; у основания вашего рта пламя столь высоких температур, что в теории, при должной настойчивости способно оплавить металл, но есть все риски потерять лицо, в буквальном смысле!",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	aoe = { radius = 6 },
	scaling = {
		hit    = { ["Исток"] = 1.5 },
		crit   = { ["Анализ"] = 1.5 },
		damage = { ["Интеллект"] = 2.5 },
	},
})
Add({
    id = "frost_nova",
    name = "Кольцо льда",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_freezingbreath",
    level = 1,
    class = "Маг",
    damageType = "frost",
    caura = 577,
    description = "Всплеск льда и холода, который детонирует с пронзительным визгом. Заклинание наносит урона холод  всем существам в области эффекта; успешный спасбросок сокращает урон вдвое. Окружающие предметы также получают урон.\n\nЗаклинатель указывает пальцем и определяет дистанцию (расстояние и высоту), на которой должно произойти кольцо льда. Область взрыва имеет радиус 3 метра, но лишь 30 сантиметров в высоту; заклинатель может контролировать её ориентацию.\n\nСущества, получившие урон от кольца льда замеляются от пронзающего их суть хлада.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	aoe = { radius = 12 },
	duration = 3,
	debuff = "eff_chilling",
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Исток"] = 0.5 },
		crit   = { ["Анализ"] = 1.5 },
		damage = { ["Интеллект"] = 0.5 },
	},
})

Add({
    id = "mana_burst",
    name = "Чародейская вспышка",
    key = "Отречение",
    icon = "Interface\\Icons\\Ability_argus_soulburst",
    level = 3,
    class = "Маг",
    damageType = "arcane",
    caura = 364,
    description = "Вы создаете область магической нестабильности вокруг себя, вызывая возмущения в пространстве; магические энергии восстают против своих заклинателей, и наносят им вред равноценный их уровню соответственно кругам заклинаний; в случае если более пяти заклятий обращаются против заклинателей, в пространстве создаётся разрыв вызывающий прорыв манадемонов.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	duration = 1,
    isConcentration = false,
	aoe = { radius = 6 },
	scaling = {
		hit    = { ["Наука"] = 1 },
		crit   = { ["Анализ"] = 1 },
		damage = { ["Интеллект"] = 1.5 },
	},
})

Add({
    id = "undetectable",
    name = "Необнаружимость",
    key = "Отречение",
    icon = "Interface\\Icons\\Inv12_apextalent_mage_touchofthearchmage",
    level = 3,
    class = "Маг",
    caura = 98,
    description = "Это заклинание защищает существо или объект от эффектов школы прорицания, скрывая их местоположение, ауру, голос или внешний вид, а также скрывая от обнаружений любого вида; необнаружимость защищает также от аналогичных магических эффектов создаваемых магическими предметами.\n\nЕсли кто-то пытается применить заклинание прорицания против защищенного существа или предмета, заклинатель должен совершить проверку прорицания с помехой, или с преимуществом, если он сильнее, или слабее того, кто наложил защитные чары.\n\nЕсли заклинание наложено на существо, оно защищает как само существо, так и его снаряжение.",
    isCantrip = false,
    resistable = true,
	duration = 1200,
    isConcentration = false,
	distance = 2.5,
    buff = "eff_undetectable",
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "antimagic",
    name = "Антимагия",
    key = "Отречение",
    icon = "Interface\\Icons\\Spell_frost_iceshock",
    level = 3,
    class = "Маг",
    caura = 734,
    description = "Это заклинание позволяет: прекратить действие текущих заклинаний, наложенных на существо или объект, временно подавить магический эффект волшебного предмета, закончить действие эффектов заклинаний внутри зоны действия рассеивания магии, или провести контрзаклинание, отменив заклятие другого волшебника. Не все заклинания можно рассеять или отменить.\n\nМагические эффекты с длительность: мгновенно нельзя рассеять, ведь они действуют быстрее, чем вступает в эффект рассеивание магии, таким образом нельзя отменить магические повреждения от огненного шара или обратить каменного персонажа обратно в живого.\n\nВы можете выбирать применение рассеивания магии в одном из трех способов: как целевое заклинание, рассевание по области или как контрзаклинание.",
    isCantrip = false,
    resistable = true,
	distance = 30,
	dispel = { "magic" },
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "abonish_magic",
    name = "Ослабление магии",
    key = "Отречение",
    icon = "Interface\\Icons\\Spell_magic_managain",
    level = 1,
    class = "Маг",
    caura = 98,
    description = "Заклинание создаёт ауру вокруг цели, которая ослабляет часть эффектов всех исцеляющих и наносящих урон заклинаний на 1 круг.",
    isCantrip = false,
    resistable = true,
	duration = 150,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_abonish_magic",
	scaling = {
		hit    = { ["Наука"] = 1, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "mage_slow",
    name = "Замедление",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_nature_slow",
    level = 3,
    class = "Маг",
    caura = 735,
    description = "Маг искажает течение времени вокруг противника. Его скорость передвижения и применения способностей уменьшается, а частота атак становится ниже.",
    isCantrip = false,
    resistable = true,
	duration = 2,
    isConcentration = false,
	distance = 30,
	debuff = "eff_slowed_mage_slow",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})

Add({
    id = "dark_vision",
    name = "Темное зрение",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Inv_12_trinket_raid_voidspire_int1_voiddragoneye",
    level = 2,
    class = "Маг",
    caura = 167,
    description = "Субъект получает возможность видеть в полной темноте в радиусе 18 м. Темновиденье дает возможность видеть только в черно-белом цвете. Заклинание темновиденья не дает возможности видеть в магической темноте.",
    isCantrip = false,
    resistable = true,
	duration = 1200,
    isConcentration = false,
	distance = 2.5,
    buff = "eff_dark_vision",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "blink",
    name = "Скачок",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_arcane_blink",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Окутавшись серебристым туманом, вы телепортируетесь на расстояние до 9 метров в свободное пространство, видимое вами.",
    isCantrip = false,
    resistable = true,
    duration = 1,
	container = "eff_blink",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "arcaneintellect",
    name = "Чародейский интеллект",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_holy_magicalsentry",
    level = 1,
    class = "Маг",
    caura = 98,
    description = "Это заклинание делает существо умнее, что влияет на проверки требующие интеллектуальной или иной деятельности; от повышения интеллекта не прибавляется мана, но in случае соревования с другими волшебниками (например, при использовании рассеивания или контрзаклинания), они получают право дополнительного преимущества.",
    isCantrip = false,
    resistable = true,
	duration = 20,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_owl_wisdom_arcaneintellect",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "mage_featherfall",
    name = "Падение перышком",
    key = "Трансмутация",
    icon = "Interface\\Icons\\Spell_magic_featherfall",
    level = 1,
    class = "Маг",
    caura = 735,
    description = "Маг замедляет падение союзников, превращая стремительное падение в плавное скольжение. Цели под действием эффекта не получают урона при приземлении.",
    isCantrip = false,
    resistable = true,
	duration = 2,
    isConcentration = false,
	distance = 2.5,
    buff = "eff_mage_featherfall",
	scaling = {
		hit    = { ["Наука"] = 1.5 },
	},
})
Add({
    id = "mana_water",
    name = "Создание воды маны",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_12_profession_enchanting_manaoil_blue",
    level = 1,
    class = "Маг",
    caura = 961,
    description = "Это заклинание наполняет пустой флакон прозрачной водой. Если заклинатель выпивает эту воду, он восстанавливает ману, которой хватит на заклинание до 3-го круга (по выбору пьющего). ",
    isCantrip = false,
    resistable = true,
    isConcentration = false,
    creates = "item_mana_water",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "mana_food",
    name = "Сотворение пищи",
    key = "Воплощение",
    icon = "Interface\\Icons\\Inv_misc_food_73cinnamonroll",
    level = 1,
    class = "Маг",
    caura = 961,
    description = "Это заклинание создаёт две буханки кислого хлеба. Съев одну буханку (что занимает 5 последовательных и непрерываемых раундов), существо восстанавливает здоровье.\n\nПо окончании действия заклинания все несъеденные буханки исчезают.",
    isCantrip = false,
    resistable = true,
    isConcentration = false,
    creates = "item_mana_food",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "frost_armor_mage",
    name = "Ледяной доспех",
    key = "Воплощение",
    icon = "Interface\\Icons\\Spell_frost_frostarmor02",
    level = 0,
    class = "Маг",
    caura = 807,
    description = "Ледяной доспех укрывает волшебника от физического, и огненного урона, повышая выживаемость, так например колотый удар клинком может вместо окончательной смерти оставить глубокое колотое ранение, а небольшая царапина и вовсе не проявится отражаясь от защитного хлада; ледяной доспех не стесняет мага в движениях, больше проявляя себя в форме ауры.\n\nЛедяной доспех из-за своей магической природы предотвращает атаки бестелесными существами, и защищает от попыток одержимости со стороны призраков.\n\nЛюбое существо, которое ударяет цель своим телом или рукопашным оружием, наносит обычный урон, но одновременно подвергается охлаждению. Заметьте, что оружие с исключительной досягаемостью (например, длинные копья) не подвергает своих владельцев этой опасности.",
    isCantrip = false,
    resistable = true,
	duration = 600,
    isConcentration = false,
	container = "eff_frost_armor_mage",
	scaling = {
		hit    = { ["Наука"] = 1, ["Исток"] = 0.5 },
	},
})
Add({
    id = "summon_familiar",
    name = "Волшебный фамилиар",
    key = "Воплощение",
    icon = "Interface\\Icons\\Ability_socererking_arcanemines",
    level = 2,
    class = "Маг",
    caura = 1301,
    description = "Маг призывает магического фамильяра — воплощение собственной силы, способное повторять отголоски его чар.\n\nКаждое сотворённое магом заклинание находит отклик в фамильяре. Вредоносные чары получают усиленный отголосок, повторяющий их разрушительную силу, а полезные и защитные заклинания распространяются на самого фамильяра. Так он способен следовать за магом, усиливая его атаки и перенимая действие его чар.\n\nФамильяр не обладает собственной волей и действует лишь как отражение магии хозяина.",
    isCantrip = false,
    resistable = true,
    duration = 10,
    isConcentration = false,
    container = "eff_summon_familiar",
})
Add({
    id = "image",
    name = "Образ",
    key = "Иллюзия",
    icon = "Interface\\Icons\\Inv_112_raidtrinkets_netheroverlaymatrix",
    level = 3,
    class = "Маг",
    caura = 98,
    description = "Маг создаёт сложную иллюзию, способную имитировать внешний вид, звук, запах и температуру. Образ можно перемещать и заставлять реагировать на происходящее вокруг.",
    isCantrip = false,
    resistable = true,
	duration = 10,
    isConcentration = false,
	distance = 20,
    container = "eff_image",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "blurred_image",
    name = "Размытый образ",
    key = "Иллюзия",
    icon = "Interface\\Icons\\Spell_nature_invisibilty",
    level = 3,
    class = "Маг",
    caura = 812,
    description = "Силуэт мага начинает мерцать и раздваиваться, затрудняя попадание по нему. Противники получают меньший шанс успешно поразить цель прямыми атаками.",
    isCantrip = false,
    resistable = true,
	duration = 20,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_evasion_blurred_image",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "mage_invisibility",
    name = "Невидимость",
    key = "Иллюзия",
    icon = "Interface\\Icons\\Ability_mage_invisibility",
    level = 2,
    class = "Маг",
    caura = 1,
    description = "Существо или объект, которого коснулись, становятся невидимыми даже для ночного зрения. Если существо что-то несет, его снаряжение тоже исчезает с поля зрения. Если Вы активируете заклинание на кого-либо, то ни Вы, ни Ваши союзники не видят этого субъекта, если только не применять способность видеть невидимое или тому подобную магию.\n\nВещи, которые уронил или бросил невидимка, становятся видимыми; подобранные вещи исчезают, если их спрятать в одежду, вещмешок или завернуть во что-либо. Свет не становится невидимым, но его источник – да (это выглядит, как свет есть, а источника освещения – нет). Любая часть снаряжения невидимки, выпирающая от него более чем на 3 метра, становится видимой, как, например, тянущаяся веревка.\n\nНевидимка может открывать двери, говорить, есть, призывать чудовищ и приказывать им, в том числе нападать; подрезать веревочные мосты, ставить ловушки, открывать клетки и т. д; Если же субъект атакует непосредственно, он сразу же становится видимым со всеми своими вещами; заклинания подобные благословлению воздействуют только на союзников, а не на врагов, и не являются атакой, даже если враги находятся в диапазоне заклинания.",
    isCantrip = false,
    resistable = true,
	duration = 10,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_stealth_mage_invisibility",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "disguise",
    name = "Маскировка",
    key = "Иллюзия",
    icon = "Interface\\Icons\\Ability_racial_dispelillusions",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Маг изменяет собственный облик, маскируя лицо, одежду, броню и снаряжение. Иллюзия меняет только внешний вид и не даёт цели чужих способностей.",
    isCantrip = false,
    resistable = true,
	duration = 100,
    isConcentration = false,
    container = "eff_disguise",
	scaling = {
		hit    = { ["Наука"] = 1 },
	},
})
Add({
    id = "detect_thougts",
    name = "Обнаружение мыслей",
    key = "Прорицание",
    icon = "Interface\\Icons\\Spell_arcane_focusedpower",
    level = 2,
    class = "Маг",
    caura = 98,
    description = "Маг проникает в поверхностные мысли ближайших существ. Чем дольше сохраняется концентрация, тем больше информации можно получить о присутствующих разумах и их намерениях.",
    isCantrip = false,
    resistable = true,
	duration = 10,
    isConcentration = true,
	distance = 20,
    container = "eff_detect_thougts",
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Интуиция"] = 0.5 },
	},
})
Add({
    id = "see_invisible",
    name = "Видеть невидимое",
    key = "Прорицание",
    icon = "Interface\\Icons\\Spell_shadow_detectlesserinvisibility",
    level = 2,
    class = "Маг",
    caura = 167,
    description = "Магические искажения становятся видимыми для заклинателя. Невидимые и бестелесные существа в пределах обзора проявляются как полупрозрачные силуэты.",
    isCantrip = false,
    resistable = true,
	duration = 100,
    isConcentration = false,
    container = "eff_see_invisible",
	scaling = {
		hit    = { ["Наука"] = 0.5, ["Интуиция"] = 0.5 },
	},
})
Add({
    id = "polymorph",
    name = "Полиморф",
    key = "Трансмутация",
    icon = "Interface\\Icons\\spell_nature_polymorph",
    level = 1,
    class = "Маг",
    caura = 98,
    description = "Маг превращает цель в безобидную форму зверя. Полиморфированное существо теряет доступ к своим обычным способностям и возвращается в исходную форму после разрушения эффекта или получения серьёзного повреждения.",
    isCantrip = false,
    resistable = true,
	duration = 3,
    isConcentration = false,
	distance = 30,
    debuff = "eff_polymorph",
	scaling = {
		hit    = { ["Наука"] = 1.5 },
	},
})Add({    id = "mage_anticurse",    name = "Развеять проклятие",	key = "Отречение",	icon = "Interface\\Icons\\Spell_nature_removecurse",    level = 1,    class = "Маг",	caura = 95,	description = "Позволяет магу разрушить цепи проклятий равных, или слабее третьему кругу; все проклятия на субъекте развеиваются, а использование заклятия на проклятом предмете позволяет от него избавиться, если проклятие лежащее на нем слабее, или равно третьему кругу магии.",    isCantrip = false,	resistable = true,	distance = 40,	dispel = "curse",})
