local addonName, SB = ...
local Add = SB.Database.AddSpell -- Короткая ссылка

Add({
    id = "shadow_bolt",
    name = "Стрела тьмы",
	key = "Разрушение",
	icon = "Interface\\Icons\\Spell_shadow_shadowbolt",
    level = 0,
    class = "Чернокнижник",
    damageType = "shadow",
    caura = 100,
	description = "Чернокнижник произносит слова, и совершает нечестивые жесты, призывая сгусток тлетворной тени, разъедающей и оскверняющей всё, до чего она дотронется. У стрелы тьмы есть характерный эффект в виде исходящего от неё зловещего шепота, расходящегося эхом по округе.\n\nВ случае попадании по цели, та получает урон темной магией и значительно теряет в боевом духе.",
    isCantrip = true,
    resistable = true,
    canCrit = true,
	distance = 20,
	scaling = {
		hit    = { ["Живучесть"] = 1 },
		crit   = { ["Исток"] = 2 },
		damage = { ["Интеллект"] = 0.6 },
	},
})
Add({
    id = "immolation",
    name = "Жертвенный огонь",
	key = "Разрушение",
	icon = "Interface\\Icons\\Spell_fire_immolation",
    level = 1,
    class = "Чернокнижник",
    damageType = "fire",
    caura = 710,
	description = "Нечестивые слова и пролитая кровь — своя или чужая — призывают демоническое пламя, которое чернокнижник передаёт врагу касанием. В начале каждого из двух своих ходов цель получает урон огнём.\n\nПламя жадно к жизненной силе — людям, растениям, всему живому. Живые сбивают его без воды с помехой, нежить — с преимуществом.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	duration = 2,
    isConcentration = false,
	distance = 20,
    debuff = "eff_immolation",
	scaling = {
		hit    = { ["Живучесть"] = 1.5 },
		crit   = { ["Рвение"] = 1 },
		damage = { ["Характер"] = 0.29 },
	},
})
Add({
    id = "burning_pain",
    name = "Жгучая боль",
	key = "Разрушение",
	icon = "Interface\\Icons\\Spell_shadow_painandsuffering",
    level = 2,
    class = "Чернокнижник",
    caura = 710,
	description = "Нечестивые слова и пролитая кровь — своя или чужая — призывают демоническое пламя, которое чернокнижник передаёт врагу касанием. В начале каждого из двух своих ходов цель получает урон огнём.\n\nПламя жадно к жизненной силе — людям, растениям, всему живому. Живые сбивают его без воды с помехой, нежить — с преимуществом.",
    isCantrip = false,
    resistable = true,
	duration = 2,
	debuff = "eff_immolation",
    canCrit = true,
	distance = 2.5,
	scaling = {
		hit    = { ["Живучесть"] = 1.5, ["Запугивание"] = 0.5 },
		crit   = { ["Рвение"] = 1 },
		damage = { ["Характер"] = 0.9 },
	},
})
Add({
    id = "soul_burn",
    name = "Ожог души",
	key = "Разрушение",
	icon = "Interface\\Icons\\Spell_fire_felimmolation",
    level = 2,
    class = "Чернокнижник",
    caura = 710,
	description = "Чернокнижник мечет в противника зелёное пламя Скверны и, поддерживая заклинание, планомерно выжигает его душу, причиняя невыразимые муки. Особенно действенно против духов и нежити.\n\nЖертва не только страдает, но и глупеет, а если колдун заиграется — может лишиться души, а с ней, скорее всего, и жизни.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	distance = 20,
	scaling = {
		hit    = { ["Живучесть"] = 1.5, ["Запугивание"] = 0.5 },
		crit   = { ["Рвение"] = 2 },
		damage = { ["Характер"] = 0.9 },
	},
})
Add({
    id = "hell_incinerate",
    name = "Адское Пламя",
	key = "Разрушение",
	icon = "Interface\\Icons\\Spell_fire_incinerate",
    level = 2,
    class = "Чернокнижник",
    damageType = "fire",
    caura = 710,
	description = "Чернокнижник разжигает демоническое пламя собственной жизненной силой и каждый раунд вспыхивает волнами адского пожара, обрушивая на окружающих Геенну огненную. Плоть его горит, но не сгорает — он ссыхается изнутри, слабея с каждой секундой.\n\nПламя держится до трёх раундов, после чего чернокнижник остаётся без сил. Повторное Адское Пламя — верная смерть.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
	duration = 3,
    isConcentration = false,
	aoe = { radius = 12 },
    container = "eff_hell_incinerate",
	scaling = {
		hit    = { ["Живучесть"] = 1.5 },
		crit   = { ["Рвение"] = 1.5 },
		damage = { ["Характер"] = 1.55 },
	},
})
Add({
    id = "rain_of_fire",
    name = "Огненный ливень",
	key = "Разрушение",
	icon = "Interface\\Icons\\Spell_shadow_rainoffire",
    level = 3,
    class = "Чернокнижник",
    damageType = "fire",
    caura = 710,
	description = "Чернокнижник складывает длани в жесте силы, выпускает собственную кровь наружу, произносит слова на демоническом наречии и выпускает с небес огненный ливень, погружая пространство в цвета алого; все существа в области получают значительный урон огнём; это заклинание может быть произнесено только снаружи.",
    isCantrip = false,
    resistable = true,
    canCrit = true,
    isConcentration = false,
	distance = 20,
	aoe = { radius = 6 },
	channel = 2,
    debuff = "eff_rain_of_fire",
	scaling = {
		hit    = { ["Живучесть"] = 1.5, ["Запугивание"] = 1 },
		crit   = { ["Рвение"] = 1 },
		damage = { ["Характер"] = 1.77 },
	},
})
Add({
    id = "demonic_swarm",
    name = "Призвать рой",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_nature_insect_swarm2",
    level = 0,
    class = "Чернокнижник",
    damageType = "shadow",
    caura = 1374,
	description = "Вы призываете рой демонических паразитов, столь малых и незначительных что они не задерживаются надолго в нашей реальности; плотоядные мухи кружат вокруг вашего противника и щедро обгладывают его плоть, нанося увечные раны. Это жуткое и неприятное зрелище в большей мере лишь увечит ваших недругов, убить оно способно разве что крысу.",
    isCantrip = true,
    resistable = true,
    canCrit = true,
	duration = 2,
    isConcentration = true,
	distance = 20,
    container = "eff_demonic_swarm",
	scaling = {
		hit    = { ["Исток"] = 1, ["Концентрация"] = 0.5 },
		crit   = { ["Рвение"] = 1 },
	},
})
Add({
    id = "summon_imp",
    name = "Призыв беса",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_summonimp",
    level = 2,
    class = "Чернокнижник",
    caura = 1374,
	description = "Вы истрачиваете осколок души и силой скверны призываете беса из Круговерти Пустоты; он во всем слушается вас, но выполняет ваши приказы неохотно, слушается приказов соответственно их букве, а не духу; in случае если вы потеряете сознание в следствии битвы, или будете убиты, демон отправляется обратно в Круговерть Пустоты.\n\nЧернокнижник может призвать, и контролировать только одного демона.",
    isCantrip = false,
    resistable = true,
	duration = 600,
    isConcentration = false,
	distance = 10,
    container = "eff_summon_imp",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 0.5 },
	},
})
Add({
    id = "demonic_armor",
    name = "Демонический доспех",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_ragingscream",
    level = 1,
    class = "Чернокнижник",
    caura = 1374,
	description = "Чернокнижник произносит слова силы, и совершает необходимые пасы руками, окружая себя демоническим доспехом; демонический доспех защищает чернокнижника от дробящих, рубящих, и колющих ударов, но столь же плохо справляется с защитой от магии. Шкура демона исцеляет чернокнижника словно заклинание исцеление незначительных ранений, закрывая тонкие порезы и защищая от незначительных повреждений.",
    isCantrip = false,
    resistable = true,
	duration = 600,
    isConcentration = false,
	container = "eff_demonic_armor",
	scaling = {
		hit    = { ["Религия"] = 1, ["Лидерство"] = 0.5 },
	},
})
Add({
    id = "health_funnel",
    name = "Канал здоровья",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_lifedrain",
    level = 2,
    class = "Чернокнижник",
    caura = 1374,
	description = "Чернокнижник может указать собственным перстом в сторону демона, и причинив себе повреждения перенаправить ему свою жизненную силу; демон исцеляется словно под воздействием легкого исцеления ранений; канал здоровья может убить чернокнижника, если тот не будет знать меры.",
    isCantrip = false,
    resistable = true,
	distance = 30,
    isHeal = true,
    channel = 3,
    duration = 3,
    onCast = { damage = 2 },
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 0.5 },
		crit   = { ["Религия"] = 1 },
		damage = { ["Выносливость"] = 1 },
	},
})
Add({
    id = "demon_breath",
    name = "Бесконечное дыхание",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_demonbreath",
    level = 1,
    class = "Чернокнижник",
    caura = 1374,
	description = "Чернокнижник прикасается к своей цели, и произносит слова силы, наделяя её (или самого себя) возможностью дышать под водой; при этом субъект не теряет возможности дышать на поверхности.",
    isCantrip = false,
    resistable = true,
	duration = 1200,
    isConcentration = false,
	distance = 2.5,
    buff = "eff_demon_breath",
	scaling = {
		hit    = { ["Религия"] = 1, ["Лидерство"] = 0.5 },
	},
})
Add({
    id = "healthstone",
    name = "Камень здоровья",
	key = "Демонология",
	icon = "Interface\\Icons\\Warlock_ healthstone",
    level = 2,
    class = "Чернокнижник",
    caura = 1374,
	description = "Чернокнижник используя нечестивые слова, смыслы, и осколок чужой души произносит слова заклинания, смачивая предмет своей кровью, под тлетворным воздействием заклинания прямо на глазах, осколок души преобразовывается в камень здоровья, что действует как исцеление от легких ранений.\n\nЧернокнижник может поддерживать существование только двух камней здоровья.",
    isCantrip = false,
    resistable = true,
    isConcentration = false,
	distance = 2.5,
    creates = "item_healthstone",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 0.5 },
	},
})
Add({
    id = "dark_amulet",
    name = "Темный оберег",
	key = "Демонология",
	icon = "Interface\\Icons\\Inv_jewelry_necklace_04",
    level = 1,
    class = "Чернокнижник",
    caura = 1374,
	description = "Чернокнижник сплетает магические символы в мистическую матрицу, ограждая себя или другого от энергии Тьмы и осквернения души и тела.\n\nОберег разрушается, поглотив:\n1-й круг — два заклинания 1-го круга или одно 2-го; от 3-го не защищает;\n2-й круг — три 1-го, или два 2-го, или одно 3-го;\n3-й круг — три 1-го, или два 2-го, или два 3-го.",
    isCantrip = false,
    resistable = true,
	duration = 600,
    isConcentration = false,
	distance = 2.5,
	buff = "eff_shield_dark_amulet",
	scaling = {
		hit    = { ["Религия"] = 1, ["Лидерство"] = 0.5 },
	},
})
Add({
    id = "summon_sayaada",
    name = "Призыв сайаада",
	key = "Демонология",
	icon = "Interface\\Icons\\Ability_warlock_randomizesuccubusincubus",
    level = 4,
    class = "Чернокнижник",
    caura = 1374,
	description = "Вы истрачиваете осколок души и силой скверны призываете суккуба или инкуба; он во всем слушается вас, но выполняет ваши приказы неохотно, слушается приказов соответственно их букве, а не духу; в случае если вы потеряете сознание в следствии битвы, или будете убиты, демон отправляется обратно в Круговерть Пустоты.\n\nЧернокнижник может призвать, и контролировать только одного демона.",
    isCantrip = false,
    resistable = true,
	duration = 600,
    isConcentration = false,
	distance = 10,
    container = "eff_summon_sayaada",
	scaling = {
		hit    = { ["Религия"] = 2, ["Лидерство"] = 1 },
	},
})
Add({
    id = "summon_voidwalker",
    name = "Призыв демона Бездны",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_summonvoidwalker",
    level = 2,
    class = "Чернокнижник",
    caura = 1374,
	description = "Вы истрачиваете осколок души и силой скверны призываете демона Бездны из Круговерти Пустоты; он во всем слушается вас, но выполняет ваши приказы неохотно, слушается приказов соответственно их букве, а не духу; в случае если вы потеряете сознание в следствии битвы, или будете убиты, демон отправляется обратно в Круговерть Пустоты.\n\nЧернокнижник может призвать, и контролировать только одного демона.",
    isCantrip = false,
    resistable = true,
	duration = 600,
    isConcentration = false,
	distance = 10,
    container = "eff_summon_voidwalker",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 0.5 },
	},
})
Add({
    id = "eye_of_kilrogg",
    name = "Око Килрогга",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_evileye",
    level = 2,
    class = "Чернокнижник",
    caura = 1374,
	description = "Чернокнижник произносит слова, совершает жесты, и использует осколок чужой души чтобы призвать в этот мир демоническое око, имеющее прямую связь с чернокнижником; усилием собственной воли колдун может отрешиться от окружающего мира, и полностью созерцать его через Око Килрогга; Око ничего не слышит, но прекрасно видит.  Оно быстро двигается по воздуху, довольно хрупкое, и видимое.",
    isCantrip = false,
    resistable = true,
	duration = 600,
    isConcentration = false,
	distance = 10,
    container = "eff_eye_of_kilrogg",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 0.5 },
	},
})
Add({
    id = "banishment",
    name = "Изгнание",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_cripple",
    level = 3,
    class = "Чернокнижник",
    caura = 1374,
	description = "Приложив правильные усилия и сказав необходимые слова, колдун может временно изгнать часть существа в Круговерть Пустоты, сделав её невосприимчивой к урону, но также неподвижной, застрявшей между двух планов; в случае если Изгнание было применено к двум существам, они могут взаимодействовать между друг-другом.\n\nЭто заклинание действует только на элементалей, демонов и иных инопланарных существ.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 3,
    isConcentration = false,
	distance = 30,
    debuff = "eff_banishment",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 1 },
	},
})
Add({
    id = "detect_invisibility",
    name = "Обнаружить невидимое",
	key = "Демонология",
	icon = "Interface\\Icons\\Sha_ability_rogue_bloodyeye_nightborne",
    level = 2,
    class = "Чернокнижник",
    caura = 1374,
	description = "Чернокнижник может сжечь демонический глаз, чтобы временно обрести возможность видеть невидимое; колдун видит сквозь иллюзии и магическую маскировку, но его всё ещё можно обмануть естественными укрытиями, такими как кусты, насыпь, или просто удачный костюм с гримом; это заклинание не всегда работает гарантированно: могущественные чары, демоны, и иные исключения останутся за полем зрения чернокнижника.",
    isCantrip = false,
    resistable = true,
	distance = 0,
    duration = 3,
    debuff = "eff_detect_invisibility",
    aoe = { radius = 18 },
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 0.5 },
	},
})
Add({
    id = "create_soulstone",
    name = "Создание камня душ",
	key = "Демонология",
	icon = "Interface\\Icons\\Inv_misc_orb_04",
    level = 5,
    class = "Чернокнижник",
    caura = 1374,
	description = "В ритуальном круге чернокнижник сплавляет осколки чужих душ и собственную жизненную силу в камень душ.\n\nПоместив в камень частицу своего духа, чернокнижник возрождается через 2 раунда после смерти, если камень при нём — в руках или сумке; затем камень рассыпается. Чужую душу камень хранит лишь целиком и не возрождает её. Привязать свою душу может лишь владеющий знаниями чернокнижника 3-го круга.",
    isCantrip = false,
    resistable = true,
    isConcentration = false,
    creates = "item_soulstone",
	scaling = {
		hit    = { ["Религия"] = 2, ["Лидерство"] = 1 },
	},
})
Add({
    id = "ritual_of_summoning",
    name = "Ритуал призыва",
	key = "Демонология",
	icon = "Interface\\Icons\\Achievement_dungeon_outland_dungeonmaster",
    level = 3,
    class = "Чернокнижник",
    caura = 1374,
	description = "Чернокнижник чертит магический круг и осколком души разрывает грань между планами. С двумя помощниками (демон тоже подойдёт) он призывает знакомого гуманоида, способного осознанно дать на это согласие.\n\nПризываемого проносит сквозь Круговерть Пустоты — можно подхватить скверну; антимагия и иные преграды блокируют перенос. После ритуала все участники истощены на 3 дня и не могут повторить обряд.",
    isCantrip = false,
    resistable = false,
	canCrit = false,
	distance = 0,
    duration = -1,
    container = "eff_ritual_exhaustion",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 1 },
	},
})
Add({
    id = "create_magic_stone",
    name = "Создание чарокамня",
	key = "Демонология",
	icon = "Interface\\Icons\\Inv_jewelcrafting_90_gem_purple",
    level = 3,
    class = "Чернокнижник",
    caura = 1374,
	description = "Из осколка души чернокнижник творит один из двух самоцветов.\n\nКамень огня расходуется: на минуту зачаровывает оружие огнём или усиливает на круг любое огненное заклинание.\n\nКамень чар при использовании снимает с заклинателя все магические эффекты и 3 раунда частично поглощает магический урон; просто носимый — усиливает тайную (не стихийную) магию.\n\nОдновременно существует лишь один камень.",
    isCantrip = false,
    resistable = true,
    isConcentration = false,
    creates = "item_magic_stone",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 1 },
	},
})
Add({
    id = "enslave_demon",
    name = "Порабощение демона",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_enslavedemon",
    level = 3,
    class = "Чернокнижник",
    caura = 1374,
	description = "Сжигая в пламени Скверны демонические рога, чернокнижник простирает длань к отродью и порабощает его на 3 раунда. Демон движется вдвое медленнее, атакует нехотя и ищет любую лазейку, чтобы обмануть приказ и навредить хозяину. Против повторного подчинения он может сопротивляться.\n\nНекоторых демонов подчинить нельзя. Под контролем — лишь один демон.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 3,
    isConcentration = false,
	distance = 30,
    debuff = "eff_enslave_demon",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 1 },
	},
})
Add({
    id = "summon_felhunter",
    name = "Призыв гончей Скверны",
	key = "Демонология",
	icon = "Interface\\Icons\\Spell_shadow_summonfelhunter",
    level = 3,
    class = "Чернокнижник",
    caura = 1374,
	description = "Вы истрачиваете осколок души и силой скверны призываете демоническую гончую; она во всем слушается вас, но выполняет ваши приказы неохотно, слушается приказов соответственно их букве, а не духу; в случае если вы потеряете сознание в следствии битвы, или будете убиты, демон отправляется обратно в Круговерть Пустоты.\n\nЧернокнижник может призвать, и контролировать только одного демона.",
    isCantrip = false,
    resistable = true,
	duration = 600,
    isConcentration = false,
	distance = 10,
    container = "eff_summon_felhunter",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 1 },
	},
})
Add({
    id = "summon_felmaunt",
    name = "Призыв коня Скверны",
	key = "Демонология",
	icon = "Interface\\Icons\\Inv_warlockmount",
    level = 4,
    class = "Чернокнижник",
    caura = 1374,
	description = "Ваших познаний в демоническом искусстве оказывается достаточно для того, чтобы воззвать к демонической разновидности коней обитающих в Круговерти Пустоты; проведя подходящий ритуал в течении 10 минут, вы призываете демонического коня в ритуальном круге. Он во всем слушается вас.",
    isCantrip = false,
    resistable = true,
	duration = 1200,
    isConcentration = false,
	distance = 10,
    container = "eff_summon_felmaunt",
	scaling = {
		hit    = { ["Религия"] = 2, ["Лидерство"] = 1 },
	},
})
Add({
    id = "planar_chain",
    name = "Планарная цепь",
	key = "Демонология",
	icon = "Interface\\Icons\\Inv_misc_steelweaponchain",
    level = 3,
    class = "Чернокнижник",
    caura = 1374,
	description = "Сжимая обрывок латунной цепи, чернокнижник указывает на инопланарную сущность — она больше не может телепортироваться или вернуться на родной план. Возрождению демона это не мешает, если его душа не поймана.\n\nСкованное существо оглушено на 3 раунда и движется вдвое медленнее — а в защитном круге и вовсе не движется.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 3,
    isConcentration = false,
	distance = 30,
    debuff = "eff_planar_chain",
	scaling = {
		hit    = { ["Религия"] = 1.5, ["Лидерство"] = 1 },
	},
})
Add({
    id = "corruption",
    name = "Порча",
	key = "Колдовство",
	icon = "Interface\\Icons\\spell_shadow_abominationexplosion",
    level = 1,
    class = "Чернокнижник",
    caura = 100,
	description = "Коснувшись жертвы, чернокнижник вкладывает в неё простую и надёжную порчу. Тлетворное проклятие точит жизненную силу: недомогание, головокружение. Взрослого малая порча лишь напугает, но при должном упорстве сгубит собаку, кошку или младенца.\n\nПорченый уязвим к болезням — чахотка станет лихой колдунье лучшим помощником.",
    isCantrip = false,
    resistable = true,
	duration = 3,
    isConcentration = false,
	distance = 30,
	debuff = "eff_corruption",
	scaling = {
		hit    = { ["Внушение"] = 1, ["Концентрация"] = 0.5 },
	},
})
Add({
    id = "curse_of_weakness",
    name = "Проклятие слабости",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_curseofmannoroth",
    level = 1,
    class = "Чернокнижник",
    caura = 100,
	description = "Проклятие обрекает несчастного на немыслимую слабость: доспехи тяжелеют, оружие не держится в руках. Цель движется вдвое медленнее, бьёт оружием слабее и легче истощается — в глуши без припасов это верная смерть.\n\nЧернокнижник поддерживает лишь одно проклятие.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 4,
    isConcentration = false,
	distance = 30,
	debuff = "eff_curse_of_weakness",
	scaling = {
		hit    = { ["Концентрация"] = 1, ["Внушение"] = 0.5 },
	},
})
Add({
    id = "curse_of_agony",
    name = "Проклятие агонии",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_curseofsargeras",
    level = 2,
    class = "Чернокнижник",
    damageType = "shadow",
    caura = 100,
	description = "Излюбленное проклятие садистов: колдун ломает бычью кость и обрекает жертву на боль, нарастающую три раунда.\n\n1-й раунд: боль пронзает разум — заклинания с помехой.\n2-й раунд: агония сковывает тело — физические атаки с помехой.\n3-й раунд: боль во всём теле — цель движется вдвое медленнее и уклоняется с помехой.\n\nЧернокнижник поддерживает лишь одно проклятие.",
    isCantrip = false,
    resistable = true,
	canCrit = true,
	duration = 3,
    isConcentration = false,
	distance = 30,
	debuff = "eff_bleeding_curse_of_agony",
	scaling = {
		hit    = { ["Внушение"] = 1.5 },
		crit   = { ["Исток"] = 1 },
		damage = { ["Интеллект"] = 0.25 },
	},
})
Add({
    id = "soul_drain",
    name = "Похищение души",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_haunting",
    level = 1,
    class = "Чернокнижник",
    damageType = "shadow",
    caura = 100,
	description = "Фундаментальное заклятие всякого, кто идёт к величию по головам. Простерев длань к добыче на грани смерти, колдун целый раунд на демоническом наречии вытягивает осколок её души и обращает его в кристалл.\n\nЭфемерных существ заклинание ранит, но не уничтожает сразу; обычных духов на время парализует мукой. Живым из плоти и крови — лишь боль.",
    isCantrip = false,
    resistable = true,
	canCrit = true,
	distance = 20,
    creates = "item_soul_shard",
    channel = 2,
	scaling = {
		hit    = { ["Концентрация"] = 1, ["Внушение"] = 0.5 },
		crit   = { ["Исток"] = 1 },
		damage = { ["Интеллект"] = 0.46 },
	},
})
Add({
    id = "life_drain",
    name = "Похищение жизни",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_lifedrain02",
    level = 2,
    class = "Чернокнижник",
    damageType = "shadow",
    caura = 100,
	description = "Нечестивое заклятие связывает тела чернокнижника и врага: колдун жадно тянет из недруга молодость и жизнь. Исцеляет как среднее исцеление ранений и старит жертву.\n\nСвязь держится целый раунд; если колдуна прервут или ранят — он оглушён на раунд. Действует только на живых из плоти и крови.",
    isCantrip = false,
    resistable = true,
	canCrit = true,
	distance = 20,
    leech = 1,
    channel = 2,
	scaling = {
		hit    = { ["Внушение"] = 1.5 },
		damage = { ["Интеллект"] = 0.9 },
	},
})
Add({
    id = "curse_of_recklessness",
    name = "Проклятие безумия",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_unholystrength",
    level = 2,
    class = "Чернокнижник",
    caura = 100,
	description = "Ломая демоническую кость, чернокнижник насылает на врага проклятие невиданной ярости. Цель не осознаёт, что под воздействием: становится вспыльчивой и раздражительной, склонной к легкомысленным и агрессивным поступкам, а в бою бросается на первого, кто перед ней.\n\nЧернокнижник поддерживает лишь одно проклятие.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 3,
    isConcentration = false,
	distance = 30,
	debuff = "eff_clumsy",
	scaling = {
		hit    = { ["Внушение"] = 1.5 },
	},
})
Add({
    id = "curse_of_elements",
    name = "Проклятие стихий",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_chilltouch",
    level = 1,
    class = "Чернокнижник",
    caura = 100,
	description = "Развеяв стихийную пыль, чернокнижник указывает на цель, и та становится уязвима к жару и холоду: легко обжигается даже кипятком и обмораживается на прогулке. Заклинания огня и холода наносят ей двойной урон. На элементалей не действует.\n\nЧернокнижник поддерживает лишь одно проклятие.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 4,
    isConcentration = false,
	distance = 30,
	debuff = "eff_vulnerable_curse_of_elements",
	scaling = {
		hit    = { ["Концентрация"] = 1, ["Внушение"] = 0.5 },
	},
})
Add({
    id = "warlock_terror_howl",
    name = "Вой ужаса",
	key = "Колдовство",
	icon = "Interface\\Icons\\Ability_warlock_howlofterror",
    level = 4,
    class = "Чернокнижник",
    caura = 100,
	description = "Чернокнижник изрекает на демоническом наречии нечто нечленораздельное, но окружающие существа ощущают невообразимый ужас на краткие мгновения, задетые струны расходятся рябью в пространстве, и в головы окружающих приходит лишь одна мысль: БЕЖАТЬ!; все противники отступают прочь на своем следующем ходу, убегая в противоположном направлении от чернокнижника. Этот эффект срабатывает на цель лишь единожды.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	distance = 30,
	debuff = "eff_fear_warlock_terror_howl",
	aoe = { radius = 9 },
    duration = 3,
	scaling = {
		hit    = { ["Внушение"] = 2 },
	},
})
Add({
    id = "curse_of_tounges",
    name = "Проклятие косноязычия",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_curseoftounges",
    level = 2,
    class = "Чернокнижник",
    caura = 100,
	description = "Сжигая язык беса, чернокнижник проклинает врага: его речь искажает демонический хор, и каждое заклинание творится на ступень дольше:\n\nмгновенное — стандартным действием;\nстандартное — за раунд;\nраундовое — целую минуту (10 ходов!).\n\nЧернокнижник поддерживает лишь одно проклятие.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 3,
    isConcentration = false,
	distance = 30,
    debuff = "eff_curse_of_tounges",
	scaling = {
		hit    = { ["Внушение"] = 1.5 },
	},
})
Add({
    id = "curse_of_darkness",
    name = "Проклятие Тьмы",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_curseofachimonde",
    level = 3,
    class = "Чернокнижник",
    caura = 100,
	description = "Сдавливая в ладонях средоточие тёмной силы, чернокнижник обрекает жертву на мучительную чувствительность к Тьме: вблизи обиталищ Древних Богов их голоса звучат громче и сильнее давят на разум, а тёмные заклинания бьют больнее.\n\nПовышенный урон наносит и тайная (не стихийная) магия — скромные магические снаряды становятся увечащими стрелами.",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 3,
    isConcentration = false,
	distance = 30,
	debuff = "eff_vulnerable_curse_of_darkness",
	scaling = {
		hit    = { ["Внушение"] = 1.5 },
	},
})
Add({
    id = "burningspirit",
    name = "Жизнеотвод",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_burningspirit",
    level = 0,
    class = "Чернокнижник",
    caura = 100,
	description = "Чернокнижники готовы платить за силу любую цену. Для Жизнеотвода колдун ранит себя ритуальным оружием — глубоко: колотые раны груди и живота, вскрытые вены; иначе мана не вернётся.\n\nПосле каждой раны — спасбросок концентрации: сложность 9 и +2 за каждую возвращённую порцию маны; в тяжёлом состоянии — 14. Сперва восстанавливается мана 1-го круга, затем 2-го; 3-й — нет.",
    isCantrip = false,
    resistable = false,
	canCrit = false,
	duration = -1,
    isConcentration = false,
    onCast = { damage = 1, mana = 2 },
})
Add({
    id = "warlock_fear",
    name = "Страх",
	key = "Колдовство",
	icon = "Interface\\Icons\\Spell_shadow_possession",
    level = 2,
    class = "Чернокнижник",
    caura = 100,
	description = "Чернокнижник указывает на цель — и, если та не слишком сильна или уже тяжело ранена, вселяет в неё невыразимый страх. Худшие кошмары встают перед глазами жертвы, и она бежит прочь, пока действует заклинание. Любой урон прерывает страх.\n\nМало кто захочет пережить такое вновь!",
    isCantrip = false,
    resistable = true,
	canCrit = false,
	duration = 5,
    isConcentration = false,
	distance = 30,
	debuff = "eff_fear_warlock_fear",
	scaling = {
		hit    = { ["Внушение"] = 1 },
	},
})
